### ISSUE TITLE
Stored procedure mapping

### ISSUE THREAD

**Issue by StandBackBurrito** [R4ND3LL/EdmxRuler#21]
Any plans to support stored procedure mapping introduced in EF 7

https://learn.microsoft.com/en-us/ef/core/what-is-new/ef-core-7.0/whatsnew#stored-procedure-mapping

**Comment by R4ND3LL** [comment]
Yes, stored procedure support is the next feature I plan to dig into.  Specifically as stand-alone functions similar to how they can be imported into an EDMX and executed from code.

The link you supplied is about linking stored procedure CUD operations to entities. 
Example:  "People_Insert",         "People_Update",         "People_Delete"

That particular approach would require you to preconfigure the "People" entity in the rule file by identifying each CUD procedure, and its parameters.  and all those procedures must exist in the DB (scaffolding will not create them)..  Is this what you're looking for, or just the general ability to execute sprocs?

**Comment by MisinformedDNA** [comment]
I'm interested in generating existing SPROCs and functions as defined in the EDMX.

**Comment by R4ND3LL** [comment]
Support just added for stored procedures and functions. (**NEW AS OF JUNE 20, 2023 v1.2.28**)

Regenerate the rules json file from EDMX in order to get the same structure that you had there.  

If instead you just want to capture the sprocs in the DB without regenerating the json, you'll need to set "IncludeUnknownFunctions" to true on the schema (rule) in question.  You can use the EFR VSIX extension to check that box.

By default, unknown function capture is off.  

This is a brand new, beta feature.  Let me know if there are any issues.

For now, it is SQL server only, and no table-valued functions.

**Comment by R4ND3LL** [comment]
SQL's table-valued functions are also supported now, btw.
