### ISSUE TITLE
EDMX Table splitting support

### ISSUE THREAD

**Issue by jdanielpa** [R4ND3LL/EdmxRuler#4]
I have the following table:

![image](https://user-images.githubusercontent.com/119625172/207632217-04d64ba3-9415-4bf1-8a70-53a9c406c4c9.png)

I want to spit the table and put the two circled properties into there own entities: TargetLensTopology and TargetLensWavefront for performance reasons.  This was easily done in the EDMX.  Here is the EDMX:

![image](https://user-images.githubusercontent.com/119625172/207643066-808c0f65-ea97-424b-a713-5b21bc2c4cd1.png)

 
I have managed to manually do it in EF Core.  I am hoping you can enhance your tool to support it as well.

Here was how I did it manually in EF Core:
1. Removed the two circled properties from the TargetLens class.
2. Created a class for each of the removed properties (TargetLensTopology and TargetLensWavefront).  I added a LensID property to each class and then the corresponding property that was deleted from TargetLens
3. In the context:

![image](https://user-images.githubusercontent.com/119625172/207638947-86dbe535-8fb0-4714-9776-3ab8cbd18225.png)

I added the two HasOne lines, commented out the IsRequired property and then added the two new entities, TargetLensTopology and TargetLensWavefront.
 
I have tested on my side and I can now load TargetLenses without getting the WavefrontData and LensData.  When I need either of these properties, I am able to either use:

(Get the Topology and Wavefront loaded into a specific TargetLens):

                 //Attach the TargetLens to the context
                var result = context.Attach(a_TargetLens);
                context.Entry(a_TargetLens).Reference(s => s.Topology).Load(); // loads Topology
                context.Entry(a_TargetLens).Reference(s => s.Wavefront).Load(); // loads Wavefront

or (Get all the TargetLenses and include the properties):

                return context.TargetLens
                    .Include(x=>x.Wavefront)
                    .Include(x=>x.Topology)
                    .ToList();

Would it be possible for your tool to read the split tables from the EDMX and generate the seperate classes and update the context automatically?

**Comment by R4ND3LL** [comment]
I'll look into it.  My first impression is that it's doable.  :thumbsup:

**Comment by jdanielpa** [comment]
So after your fix to Not Mapped for columns, I moved the custom modelBuilder code I circled above to a new partial class which is automatically called at the end of OnModelCreating() :

    public partial class NextGenPlasticsEntities
    {
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TargetLens>(entity =>
            {
                entity.HasOne(o => o.Topology).WithOne().HasForeignKey<TargetLensTopology>(o => o.LensID);
                entity.HasOne(o => o.Wavefront).WithOne().HasForeignKey<TargetLensWavefront>(o => o.LensID);
            });

            modelBuilder.Entity<TargetLensTopology>(entity =>
            {
                entity.HasKey(e => e.LensID);
                entity.ToTable("TargetLens");
            });

            modelBuilder.Entity<TargetLensWavefront>(entity =>
            {
                entity.HasKey(e => e.LensID);
                entity.ToTable("TargetLens");
                entity.Property(e => e.WavefrontData).IsRequired();
            });
        }

With that, I can run the scaffolding and I get what I need!  I do not have to modify any classes which is perfect.  

If you can support table splitting automatically, that would be great but with the workflow above, it is pretty quick and easy to do it manually.

The bigger issue is definitely the TPH need:
https://github.com/R4ND3LL/EntityFrameworkRuler/issues/3

Thoughts?

**Comment by R4ND3LL** [comment]
[Design](https://www.nuget.org/packages/EntityFrameworkRuler.Design/) package v1.2.0 now contains support for inheritance, table splitting, comments, and other features.  The Editor VSIX package has also been updated accordingly.  

The approach taken here is the ability to add annotations to any element in the entity hierarchy (table, property, navigation).  Whatever annotations are specified in the JSON will be applied to the corresponding entity element during the scaffolding phase.  This means that EFR now supports any feature that is customizable via annotations in EF, which is virtually everything (EF stores all configurations as annotations).   

There is one catch.  The T4 templates may need to be updated to support the annotation feature you're after because the default templates do not expect many kinds of annotations to be generated in the scaffolding phase.  

For table splitting, however, I don't think T4 changes are required.  Let me know how this works for you.
