### ISSUE TITLE
Setting a column to Not Mapped is not saved

### ISSUE THREAD

**Issue by jdanielpa** [R4ND3LL/EdmxRuler#5]
I am trying to set 2 columns to Not Mapped since I do not want them showing in the TargetLens class.  When I check the Not Mapped options, the UI updates showing the properties marked out:

![image](https://user-images.githubusercontent.com/119625172/207686045-f0fcdcc9-d4a8-4808-82e5-375a450899a0.png)

However, after I save and re-open the Rule Editor, the columns are no longer set to Not Mapped.

**Comment by R4ND3LL** [comment]
Fixed in v1.1.7 (just published) and VSIX v1.0.70

**Comment by jdanielpa** [comment]
Validated it is fixed - thanks!

**Comment by R4ND3LL** [comment]
inheritance support is on the way, however, may end up requiring some configuration adjustments after scaffolding (using partial config methods) because of what appears to be limitations in EF scaffolding/code generation (very much due to the fact that they never expected to ever support the generation of inheritance code etc).

**Comment by jdanielpa** [comment]
That is good news!  Based on the fact they didn't expect to support inheritance code, does this point to a potential issue on my side?  I don't want to develop something that is not following best practices.

**Comment by R4ND3LL** [comment]
They don't support it simply due to the fact that the information about hierarchical strategies (TPH) and (discriminator conditions) are not present in the DB.  The scaffolding process relies 100% on what's available in the DB so any feature that can't be inferred directly by the DB is not supported.  Using EFR to fill that gap is definitely fine.
